version: '3.7'

services:
  grafana:
    build: './configuration/grafana'
    ports:
      - 3000:3000
    user: "$UID:$GID"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      monitoring:
        aliases:
            - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9000:9000
    user: "$UID:$GID"
    volumes:
      - ./configuration/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
            - prometheus
networks:
  monitoring:

