spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8189}

jwt:
  secret: axioma-app
  expiration: 604800
  header: Authorization

